### PR TITLE
fix: warnings/errors messages

### PR DESCRIPTION
**Pull request by fvcci**
Running npm run build displays a christmas tree of colours when done on the main branch. Let's fix all of them.

This review covers changes to the following files:
QrScanner.tsx, QRScanner2.tsx, middleware.ts, admin.tsx, and scanner.tsx

## Summary by CodeRabbit

- **New Features**
	- Enhanced QR code scanning and decoding functionality.
- **Bug Fixes**
	- Resolved issues with camera selection in QR code scanning.
- **Refactor**
	- Removed unused code and variables related to QR scanning and role-based access control.
	- Replaced `img` tag with `Image` component for better performance and optimization.
- **Chores**
	- Commented out role-based access control function for future investigation and implementation.

### CODE REVIEW

**Comment by fvcci** [comment]
this PR is currently not ready to submit yet. I don't know if one of the image changes I made worked because I can't run portal rn

**Comment by fvcci** [comment]
apparently try catch blocks can't have an error type that is other than "any" or unknown" so the
./src/pages/api/cal.ts:10:19  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
can't always be met.

**Review by Krish120003 — APPROVED** [review]
looks good!

**Comment by fvcci** [comment]
@Krish120003 did you check that the
```Removed unused state variables and replaced the img tag with the Image component from Next.js.```
change works? I can't figure out how to login to the dashboard on my system 🥲

**Pull request merged**
